name: ClaimTeleport
main: me.Albert.Claimteleport.Main
version: 1.0.6
author: Albert
commands:
    claimteleport:
        description: Teleport to a Claim
        usage: /ClaimTeleport
        aliases: [ctp, claimtp]
    ctpreload:
        description: Reload Plugin Config
        permission: ctp.reload
    